security:
  password_hashers:
    Symfony\Component\Security\Core\User\InMemoryUser:
      algorithm: bcrypt
      cost: 4

  providers:
      dev_users:
          memory:
              users:
                  admin:
                      password: '$2a$04$TlaN1HnnTd7ffcYjekQyQuyVRkWjjEBWfZ7sMJVV6HN.mE5qaxT4O' # admin
                      roles: ['ROLE_ADMIN', 'ROLE_USER']

  firewalls:
      dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false
      
      main:
          lazy: true
          provider: dev_users  # Utilise le provider dev
          
          form_login:
              login_path: login
              check_path: login
              default_target_path: dashboard
              enable_csrf: false
          
          logout:
              path: logout
              target: login
