version: "3.8"
 
services:
  php:
    container_name: portail_php
    image: portail_cyber-php:latest
    hostname: portail_php
    volumes:
      - code_volume:/var/www/html
    networks:
      - internal
    command: >
      sh -c "cp -r /var/www/html/. /code_volume && php-fpm"  # copie auto du code dans le volume
    mem_limit: 1024m
    cpus: 1
 
  nginx:
    image: nginx:latest
    container_name: portail_nginx
    hostname: portail_nginx
    volumes:
      - code_volume:/var/www/html
      - /var/lib/docker/volumes/portail-cyber/nginx/conf.d:/etc/nginx/conf.d
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.cyber.rule=Host(`portail-cyber.unicancer.local`)"
       - "traefik.http.routers.cyber.entrypoints=websecure"
       - "traefik.http.routers.cyber.tls=true"
       - "traefik.http.services.cyber.loadbalancer.server.port=80"
       - "traefik.docker.network=proxy"
    depends_on:
      - php
    networks:
      - proxy
      - internal
    mem_limit: 1024m
    cpus: 1
 
volumes:
  code_volume:
 
networks:
  proxy:
     name: proxy
  internal:
    driver: bridge