services:
  php:
    build: .
    container_name: portail_php
    volumes:
      - ./symfony:/var/www/html
    networks:
      - portail_net

  nginx:
    image: nginx:latest
    container_name: portail_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./symfony:/var/www/html
    depends_on:
      - php
    networks:
      - portail_net

networks:
  portail_net:
    driver: bridge
